### PR TITLE
Check matrix elements not TopLoc_Location.IsIdentity()

### PR DESCRIPTION
**Pull request by JoeLambourne**
# Symptom 

```
  File "/home/lambouj/projects/occwl/src/occwl/face.py", line 202, in specific_surface
    assert self.topods_shape().Location().IsIdentity(), \
AssertionError: Requesting surface for transformed face.             Call solid.set_transform_to_identity() to remove the transform             or compound.Transform(np.eye(4)) to bake in t
he assembly transform
```

This is warning you that you are trying to get the surface for a face, but the face has been transformed.  The face is not where you think it is.

# Problem

The assert tells you that to fix the problem you just need to bake any transforms on the solid into the underlying surfaces.   But that fix don't really stop things asserting.

# Solution
`TopLoc_Location.IsIdentity()` is actually telling fibs.  The transform was an identity, it's just that it was set as a geometric identity matrix rather than by calling  `TopLoc_LocationIdentity()`.  Hence the "I'm an identity transform" flag isn't set.   Let's check the actual elements.

# Verification

Unit tests ran and passed

### CODE REVIEW

**Review by pradeep-pyro — APPROVED** [review]
This looks good, nice catch. When setting the transform with a matrix, would it be worth checking if the matrix is an identity matrix and calling the `Location().Identity()` method?

**Comment by JoeLambourne** [comment]
> This looks good, nice catch. When setting the transform with a matrix, would it be worth checking if the matrix is an identity matrix and calling the `Location().Identity()` method?

In the `Shape.transform()` function.  That's a good idea

**Comment by JoeLambourne** [comment]
I added more functions to try to set the transforms for faces and edges and to check for applying the identity transform.

**Review by pradeep-pyro — APPROVED** [review]
The changes look good to me.

**Pull request merged**
