### PR TITLE
Offscreen renderer

### PR DESCRIPTION
**Pull request by pradeep-pyro**
Moved reusable functionalities from `Viewer`  to `_BaseViewer` and derived an `OffscreenRenderer` class that can be used for batch rendering. A small example has been added to `examples/ex7_offscreen_rendering.py`.

Additionally, exposed more functionalities in the viewer API for:
- Showing/hiding face boundaries
- Switching between Gouraud, Phong or flat shading
- Toggling antialiasing
- Showing/hiding the XYZ-axes widget

### CODE REVIEW

**Review by JoeLambourne — APPROVED** [review]
The changes all look good.

The viewer stopped working for me on windows now.   Anything which includes `simple_gui` doesn't work at all.

For linux (without a user logged into a desktop) I need the commands

```
Xvfb :10 -ac -screen 0 1024x768x24
```
Then run like this

```
DISPLAY=:10 python -m src.my_module 
```

**Comment by pradeep-pyro** [comment]
The `Viewer` related examples worked on Windows for me. Did the `Viewer` stop working for your after the changes I made in this PR? Sometimes I find that changing the backend to "wx" helps, but not sure if this will help for your problem.

**Comment by JoeLambourne** [comment]
> Did the Viewer stop working for your after the changes I made in this PR?

No.  I think it's related to the python environment.  Googling suggested that it stopped working in some old version of occ.   It would be interesting to know if it still works if you build a new environment from scratch.

**Comment by pradeep-pyro** [comment]
I created a new environment from scratch and it works. If you haven't tried the `wx` backend, then give it a shot. The `pyqt5` backend doesn't work for me on Windows.

**Pull request merged**
