### PR TITLE
Update the occwl version to 0.0.3.   Remove deprecated functions

### PR DESCRIPTION
**Pull request by JoeLambourne**
# Why?
Some critical bug fixes need to be released under a new version number.  These include support for compound solids (PR#3) and support for multi-body assemblies with non-identity transforms (PR#6)

# What?

- Update the version number to 0.0.3
- Remove all the deprecated function
- Fix the unit tests

# Verification

- Built a conda package and all the unit tests pass when the package is run
- Testing the BRepNet pipeline now

### CODE REVIEW

**Review by meltzerpete — APPROVED** [review]
I guess it depends who else is already using this package, but is it worth following semantic versioning? i.e. in this case is removal of deprecated functions considered a 'breaking change' so requiring a major version increment?

**Comment by JoeLambourne** [comment]
> I guess it depends who else is already using this package, but is it worth following semantic versioning? i.e. in this case is removal of deprecated functions considered a 'breaking change' so requiring a major version increment?

Good point @meltzerpete.   Perhaps we should go for `1.0.0`.  What do you think @pradeep-pyro ?

**Comment by pradeep-pyro** [comment]
That's a good point @meltzerpete .

I think the major bump in semver is only required after we go past 1.0. For 0.y.x releases where the API is not stable, the bump is not mandatory. When we deprecated the functions, e.g. [here](https://github.com/AutodeskAILab/occwl/blob/main/src/occwl/face.py#L488), we specified that they'll be removed in 0.0.3, so I think it's fine to go with this version.

Alternatively, we can bump the minor version number rather than the patch number to something like 0.1.0.

I'd suggest saving the 1.0 version for later when we use the library more and make the API stable.

**Review by pradeep-pyro — APPROVED** [review]

**Comment by JoeLambourne** [comment]
OK.   Let's go with the version number we have now so I don't have to make additional changes

**Pull request merged**
