### PR TITLE
Shell class

### PR DESCRIPTION
**Pull request by pradeep-pyro**
This PR adds a `Shell` class and support for iterating over them in `Solid` and `Compound`.
`Shell` objects can be passed to `Viewer` for displaying.
`occwl.graph.face_adjacency` and `occwl.graph.vertex_adjacency` now accept `Shell`s.

### CODE REVIEW

**Review by JoeLambourne — APPROVED** [review]
This looks good.  

Do you have an understanding for the rules for solids and shells?    The kinds of things it's sometimes useful to understand are:

- Does a solid need to be closed or can it have open edges?
- Does a shell need to be closed?  I would usually assume it can can open edges.
- Can a shell contain edges which are not attached to any face?  i.e. can it represent a bag of wireframe?

These are the kinds of things which would be useful in the very top comment section for compound, solid and shell.  Sadly I don't know the answers

**Comment by pradeep-pyro** [comment]
My understanding is that Solids have to be closed while Shells can be open but connected. A bag of wireframe sounds like a Compound to me.

I empirically found this out while using the sewing API where the type of the result can be a `Solid`, `Shell` or `Compound`. If the faces to be sewed are all closed and watertight then we get a `Solid`. If they are connected but open we get a `Shell`. If not, we get a `Compound`.

I will look more closely into this before merging the PR.

**Comment by pradeep-pyro** [comment]
The OCCT docs have this table explaining various TopoDS entities.
image

I think our assumptions are right. Solid has to be a bounded 3D space, Shell has to be a connected set of faces, and Compound can be arbitrary collections of shapes.

Does this clarify Joe? We can add some unit tests if we want to be more certain.

**Comment by JoeLambourne** [comment]
> If the faces to be sewed are all closed and watertight then we get a Solid. If they are connected but open we get a Shell. If not, we get a Compound.

That's super useful to know.  Do you keep track of the number of `Solid`, `Shell` and `Compound` generated?  I guess this only matters if you want to use the output in downstream modeling.

**Comment by pradeep-pyro** [comment]
I don't keep track of that, but that should be easy to do.

**Pull request merged**
